name: Pylint

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      python-version: "3.9"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  build:
    name: Build and Push image
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Image to DockerHub
      env:
        DOCKERHUB_REPO: ajay372
        IMAGE_NAME: rtail-client
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t $DOCKERHUB_REPO/$IMAGE_NAME:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image to DockerHub..."
        docker push $DOCKERHUB_REPO/$IMAGE_NAME:${GITHUB_REF##*/}-$git_hash
        echo "::set-output name=image::$DOCKERHUB_REPO/$IMAGE_NAME:${GITHUB_REF##*/}-$git_hash"